bridge:
  domain:
    br_default:
      vlan:
        5: {}
interface:
  eth0:
    ipv4:
      dhcp-client:
        set-hostname: enabled
        state: enabled
    type: eth
    vrf: mgmt
  lo:
    ipv4:
      address:
        192.168.255.1/32: {}
    type: loopback
  swp1:
    link:
      state:
        up: {}
    type: swp
  vlan5:
    ipv4:
      address:
        10.10.10.1/24: {}
    type: svi
    vlan: 5
router:
  bgp:
    state: enabled
system:
  hostname: server01
vrf:
  default:
    router:
      bgp:
        state: enabled
        autonomous-system: 65301
        router-id: 192.168.255.1
        address-family:
          ipv4-unicast:
            state: enabled
            network:
              10.10.10.0/24: {}
              192.168.255.1/32: {}
            redistribute:
              connected:
                state: enabled
              static:
                state: enabled
        neighbor:
          swp1:
            remote-as: external
            type: unnumbered
      static:
        10.10.10.0/24:
          address-family: ipv4-unicast
          via:
            lo:
              type: interface