bridge:
  domain:
    br_default:
      vlan:
        '5': {}
interface:
  lo:
    ipv4:
      address:
        192.168.255.1/32: {}
    type: loopback
  swp1:
    ipv4:
      address: {}
    type: swp
  swp1,vlan5:
    link:
      state:
        up: {}
  vlan5:
    ipv4:
      address:
        10.10.10.1/24: {}
    type: svi
    vlan: 5
router:
  bgp:
    state: enabled
vrf:
  default:
    router:
      bgp:
        state: enabled
        autonomous-system: 65301
        router-id: 192.168.255.1
        address-family:
          ipv4-unicast:
            state: enabled
            network:
              192.168.255.1/32: {}
            redistribute:
              connected:
                state: enabled
        neighbor:
          swp1:
            remote-as: external
            type: unnumbered